const base='http://localhost:4000/api';
async function login(username:string){const r=await fetch(base+'/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password:'Admin123'})});if(!r.ok)throw new Error(`${username} login: ${await r.text()}`);return r.headers.get('set-cookie')!.split(';')[0]}
async function call(cookie:string,path:string,method='GET',body?:any){const r=await fetch(base+path,{method,headers:{cookie,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw new Error(`${method} ${path}: ${r.status} ${await r.text()}`);return r.status===204?null:r.json()}
async function main(){
 const admin=await login('admin_mutu'),auditor=await login('auditor'),p4mp=await login('p4mp'),auditee=await login('auditee'),kepala=await login('kepala_unit'),verifier=await login('verifikator');
 const boot=await call(admin,'/legacy/bootstrap'),users=await call(admin,'/users');const unit=boot.units.find((x:any)=>x.code==='BUK'),auditorUser=users.find((x:any)=>x.username==='auditor');
 const code='AMI-FLOW-2028-001';let program=(await call(admin,'/legacy/audit-programs')).find((x:any)=>x.code===code);if(!program)program=await call(admin,'/legacy/audit-programs','POST',{code,name:'Uji Workflow Audit Interaktif BUK 2028',auditYear:2028,startDate:'2028-08-01',endDate:'2028-09-30',status:'PLANNED'});
 let workspace=(await call(admin,'/audit-workspaces')).find((x:any)=>x.unitId===unit.id&&x.auditYear===2028);if(!workspace)workspace=await call(admin,'/audit-workspaces','POST',{unitId:unit.id,auditYear:2028,programId:program.id});
 await call(admin,`/audit-flow/workspaces/${workspace.id}/team`,'POST',{userId:auditorUser.id,role:'AUDITOR'});await call(admin,`/audit-workspaces/${workspace.id}/generate-instrument`,'POST');
 let detail=await call(auditor,'/audit-flow/'+workspace.id),q=detail.questions[0];await call(auditor,'/audit-flow/questions/'+q.id,'PATCH',{questionSnapshot:q.questionSnapshot+' (hasil telaah auditor)',moduleCode:q.moduleCode,required:q.required,weight:q.weight});await call(auditor,`/audit-flow/workspaces/${workspace.id}/instrument/submit`,'POST',{note:'Mohon verifikasi P4MP.'});
 await call(p4mp,`/audit-flow/workspaces/${workspace.id}/instrument/return`,'POST',{note:'Perjelas objek pemeriksaan pada pertanyaan pertama.'});detail=await call(auditor,'/audit-flow/'+workspace.id);q=detail.questions[0];await call(auditor,'/audit-flow/questions/'+q.id,'PATCH',{questionSnapshot:q.questionSnapshot+' — objek: rekaman pelaksanaan unit',moduleCode:q.moduleCode,required:q.required,weight:q.weight});await call(auditor,`/audit-flow/workspaces/${workspace.id}/instrument/submit`,'POST',{note:'Perbaikan telah dilakukan.'});await call(p4mp,`/audit-flow/workspaces/${workspace.id}/instrument/approve`,'POST',{note:'Disetujui dan dipublikasikan ke Auditee.'});
 detail=await call(auditee,'/audit-flow/'+workspace.id);for(let i=0;i<detail.questions.length;i+=25)await Promise.all(detail.questions.slice(i,i+25).map((x:any,n:number)=>call(auditee,'/audit-flow/assessments/'+x.assessment.id,'PATCH',{response:`Implementasi butir ${i+n+1} telah dijalankan dan bukti tersedia.`,score:3})));
 await call(auditee,`/audit-flow/workspaces/${workspace.id}/evidences`,'POST',{auditQuestionId:detail.questions[0].id,evidenceType:'SOP',title:'Dokumen Bukti Uji Workflow',fileName:'bukti-workflow.txt',mimeType:'text/plain',fileBase64:'data:text/plain;base64,'+Buffer.from('Bukti transaksi workflow SAMI-NONAK').toString('base64'),confidentiality:'INTERNAL'});await call(auditee,`/audit-flow/workspaces/${workspace.id}/assessments/submit`,'POST');await call(kepala,`/audit-flow/workspaces/${workspace.id}/assessments/approve`,'POST');
 detail=await call(auditor,'/audit-flow/'+workspace.id);q=detail.questions[0];await call(auditor,`/audit-flow/workspaces/${workspace.id}/workpapers`,'POST',{auditQuestionId:q.id,sampleDescription:'Sampel dokumen dan wawancara',interviewee:'Kepala Unit',objectiveEvidence:'Dokumen tersedia namun evaluasi belum lengkap',auditorAnalysis:'Terdapat kesenjangan minor',auditStatus:'NC_MINOR',maturityScore:2});const finding=await call(auditor,`/audit-workspaces/${workspace.id}/findings`,'POST',{auditQuestionId:q.id,findingType:'NC_MINOR',criteriaRegulation:'Standar Tata Kelola Polbeng',criteriaIso:'ISO 9001:2015 Klausul 9.1',condition:'Evaluasi berkala belum terdokumentasi lengkap.',objectiveEvidence:'Tidak ditemukan laporan evaluasi semester.',gapStatement:'Pelaksanaan evaluasi tidak sesuai jadwal.',riskImpact:'Dokumen tidak mutakhir berpotensi digunakan.',dueDate:'2028-10-30'});await call(auditor,'/audit-flow/findings/'+finding.id+'/open','POST');
 const action=await call(auditee,`/findings/${finding.id}/corrective-actions`,'POST',{correction:'Melakukan evaluasi dokumen segera.',analysisMethod:'5 WHY',rootCauseStatement:'PIC dan kalender evaluasi belum ditetapkan.',correctiveAction:'Tetapkan PIC, kalender, dan monitoring evaluasi.',successIndicator:'100% dokumen dievaluasi tepat waktu.',targetDate:'2028-10-30'});await call(auditee,'/audit-flow/actions/'+action.id+'/progress','POST',{progressPercent:100,progressNote:'Seluruh tindakan selesai dan bukti tersedia.'});await call(verifier,`/corrective-actions/${action.id}/verifications`,'POST',{implementationResult:'Tindakan terimplementasi dan bukti dapat ditelusuri.',effectivenessResult:'Efektif mencegah pengulangan.',status:'EFFECTIVE'});await call(admin,`/audit-flow/workspaces/${workspace.id}/close`,'POST');await call(admin,`/audit-flow/workspaces/${workspace.id}/print`,'POST',{type:'AUDIT_REPORT'});
 const done=await call(admin,'/audit-flow/'+workspace.id);console.log(JSON.stringify({program:done.workspace.program.code,workspaceId:workspace.id,status:done.workspace.status,instrument:done.workspace.instrumentStatus,questions:done.questions.length,assessments:done.questions.filter((x:any)=>x.assessment?.responseStatus==='APPROVED').length,evidences:done.evidences.length,workpapers:done.workpapers.length,findings:done.findings.map((x:any)=>x.status),actions:done.actions.map((x:any)=>x.status),prints:done.prints.length},null,2));
}
main().catch(e=>{console.error(e);process.exit(1)});
